CREATE TABLE sucursales(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE productos(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	codigo VARCHAR(255) NOT NULL UNIQUE,
	descripcion VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE usuarios (
	usuario_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	usuario_nick VARCHAR(255) NOT NULL UNIQUE,
	usuario_nombre VARCHAR(255) NOT NULL,
	usuario_apellidos VARCHAR(255) NOT NULL,
	usuario_password VARCHAR(255) NOT NULL,
	usuario_role VARCHAR(255) NOT NULL,
    PRIMARY KEY(usuario_id),
	usuario_sucursal INT UNSIGNED NOT NULL,
	FOREIGN KEY(usuario_sucursal) REFERENCES sucursales(id) ON DELETE CASCADE
);

CREATE TABLE sucursal(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    producto BIGINT UNSIGNED NOT NULL,
	precioCompra DECIMAL(5, 2) NOT NULL,
	precioVenta DECIMAL(5, 2) NOT NULL,
    existencia INTEGER UNSIGNED NOT NULL,
    sucursal INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(sucursal) REFERENCES sucursales(id) ON DELETE CASCADE,
    FOREIGN KEY(producto) REFERENCES productos(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE ventas(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fecha DATETIME NOT NULL,
	total DECIMAL(7,2),
    estado VARCHAR(255) NOT NULL,
    corte TINYINT NOT NULL,
    sucursal INT UNSIGNED NOT NULL,
    usuario INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(id),
    FOREIGN KEY(sucursal) REFERENCES sucursales(id) ON DELETE CASCADE,
    FOREIGN KEY(usuario) REFERENCES usuarios(usuario_id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE productosVendidos(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	cantidad BIGINT UNSIGNED NOT NULL,
    precioVenta DECIMAL(5, 2) NOT NULL,
	producto BIGINT UNSIGNED NOT NULL,
	venta BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
	FOREIGN KEY(venta) REFERENCES ventas(id) ON DELETE CASCADE,
	FOREIGN KEY(producto) REFERENCES productos(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE devoluciones(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fecha DATETIME NOT NULL,
	total DECIMAL(7,2),
    venta BIGINT UNSIGNED NOT NULL,
	usuario INTEGER UNSIGNED NOT NULL,
    corte TINYINT NOT NULL,
	PRIMARY KEY(id),
    FOREIGN KEY(venta) REFERENCES ventas(id) ON DELETE CASCADE,
    FOREIGN KEY(usuario) REFERENCES usuarios(usuario_id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE productosDevueltos(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	cantidad BIGINT UNSIGNED NOT NULL,
    producto BIGINT UNSIGNED NOT NULL,
	devolucion BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
	FOREIGN KEY(devolucion) REFERENCES devoluciones(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


CREATE TABLE entradas(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    fecha DATETIME NOT NULL,
    total DECIMAL(7,2),
    estado VARCHAR(255) NOT NULL,
    sucursal INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
	FOREIGN KEY(sucursal) REFERENCES sucursales(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE cortes(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	fecha DATETIME NOT NULL,
	total DECIMAL(7,2),
    sucursal INT UNSIGNED NOT NULL,
    usuario INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY(id),
    FOREIGN KEY(sucursal) REFERENCES sucursales(id) ON DELETE CASCADE,
    FOREIGN KEY(usuario) REFERENCES usuarios(usuario_id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;

CREATE TABLE productosBaja(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    producto BIGINT UNSIGNED NOT NULL,
    cantidad BIGINT UNSIGNED NOT NULL,
    sucursal INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
	FOREIGN KEY(producto) REFERENCES productos(id) ON DELETE CASCADE,
    FOREIGN KEY(sucursal) REFERENCES sucursales(id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8;


INSERT INTO sucursales VALUES(null,"MERCADO 5 DE FEBRERO");
INSERT INTO sucursales VALUES(null,"CENTRO BOLIVAR");

INSERT INTO usuarios VALUES(null,'admin','Genaro','Laureano Mendez','admin','administrador',1);
INSERT INTO usuarios VALUES(null,'user','Genaro','Laureano Mendez','user','usuario',1);

